export default {
  requestTypes: {
    traffic: 'Traffic',
    overtime: 'Overtime',
    'eligible-leave': 'Eligible-Leave',
    'sick-leave': 'Sick-Leave',
    'incentive-leave': 'Incentive-Leave',
    mission: 'Mission',
    'hourly-leave': 'Hourly-Leave',
    'manual-leave': 'Manual-Leave',
    'manual-entry': 'Manual-Entry',
  },
  shiftTypes: {
    'full-time': 'Full-Time',
    'part-time': 'Part-Time',
    hourly: 'Hourly',
  },
  weekDays: {
    saturday: 'Saturday',
    sunday: 'Sunday',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    1: 'Saturday',
    2: 'Sunday',
    3: 'Monday',
    4: 'Tuesday',
    5: 'Wednesday',
    6: 'Thursday',
    7: 'Friday',
  },
  roles: {
    admin: 'Admin',
    manager: 'Manager',
    employee: 'Employee',
  },
  genders: {
    male: 'Male',
    female: 'Female',
    other: 'Other',
  },
}
